remote_theme: "mmistakes/minimal-mistakes"
baseurl: /MegaMan
repository: "khazelrigg/MegaMan"
include: ["_pages"]
teaser: /assets/img/teaser.jpg

author:
    name   : "Kameron Hazelrigg"
    bio    : "I sometimes code stuff"
    avatar : "https://avatars2.githubusercontent.com/u/16183861?s=460&v=4.jpg"

defaults:
   - scope:
         path: ""
         type: posts
     values:
         layout: single
         author_profile: true
         read_time: true
         share: true
         related: true
         image: true
   - scope:
         path: ""
         type: pages
     values:
           layout: single

