remote_theme: "mmistakes/minimal-mistakes"
baseurl: /MegaMan
repository: "khazelrigg/MegaMan"
include: ["_pages"]
teaser: /assets/img/teaser.jpg

author:
    name   : "Kameron Hazelrigg"
    avatar : "/assets/img/avatar.jpg"

defaults:
   - scope:
         path: ""
         type: posts
     values:
         layout: single
         author_profile: true
         read_time: true
         share: true
         related: true
         image: true
   - scope:
         path: ""
         type: pages
     values:
           layout: single

